name: 'Template Continuous Following'
description: 'Check for updates in template files and create a pull request with changes'
inputs:
  config-file:
    description: 'Path to the configuration JSON file'
    default: 'tmpl_cf.json'
  token:
    description: 'GitHub personal access token'
    default: ${{ github.token }}

runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    ACCESS_TOKEN: ${{ inputs.access-token }}
    CONFIG_FILE_PATH: ${{ inputs.config-file }}
